### ISSUE TITLE
Images not displaying correctly

### ISSUE THREAD

**Issue by banbar** [banbar/GMT-456-GIS-Programming#17]
@afkHub : The images on the referenced page is not displaying correctly: https://gmt456-documentation.readthedocs.io/en/latest/rst/intro.html

**Comment by afkHub** [comment]
This page created by adding the "md extension file read" feature in "conf.py" and directly upload the "group2.md" file ( https://github.com/banbar/GMT-456-GIS-Programming/blob/master/midterm_projects/2020-21/group2.md ).
That is, the images are not visible because I put them directly in the group2.md file without any editing.
So I'll delete the md file and edit this page later.

**Comment by afkHub** [comment]
@banbar 
I changed .md extension to .rst extension and I edited. Now images is displaying correctly: https://gmt456-documentation.readthedocs.io/en/latest/rst/intro.html 

Also, docstrings part appears now: https://gmt456-documentation.readthedocs.io/en/latest/rst/save_attributes.html
But it needs to be edit. I will do this later too.
